name: Test
on:
  - push
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        label:
          - FOO
          - BAR
        test-file:
          - "update-from-v4.sh"
          - "downgrade-to-v4.sh"
          - "install-newly.sh local"
          - "install-newly.sh v5"
          - "install-newly.sh lts"
          - "update-to-next-version.sh"
          - "update-to-next-version-with-backward-compat-for-v4.sh"
          - "update-to-next-version-service-status.sh"
        include:
          - label: FOO
            rake-job: rockylinux-8
            test-lxc-image: images:rockylinux/8
          - label: BAR
            rake-job: almalinux-9
            test-lxc-image: images:almalinux/9
          - test-file: update-to-next-version-service-status.sh
            args: hogehoge
          - test-file: update-to-next-version-service-status.sh
            args: fugafuga
    steps:
      - name: Test
        run: |
          echo "${{ matrix.label }} ${{ matrix.test-file }} ${{ matrix.test-lxc-image }} ${{ matrix.args }}"
